fix: correct shebang

diff --git a/bin/.local/bin/git-for-each-run b/bin/.local/bin/git-for-each-run
--- a/bin/.local/bin/git-for-each-run
+++ b/bin/.local/bin/git-for-each-run
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -euo pipefail
 
 JOBS="${JOBS:-16}"     # set this to the number of parallel jobs, only works if xargs or parallel are installed - attention, output of the commands will be interlaced / mixed for xargs
 VERBOSE="${VERBOSE:-}" # set this to 1
 V=
 if [ "${VERBOSE}" = "1" ]; then
-    V="-t"
+	V="-t"
 fi
 
 SCRIPT="$(mktemp)"
@@ -19,17 +19,17 @@ EOF
 chmod a+x "${SCRIPT}"
 
 if type parallel &>/dev/null; then
-    find . -type d -name .git -printf '%h\n' | parallel "-j${JOBS}" ${V} -k sh -eo pipefail -c "echo && cd {} && echo {} && ${SCRIPT}"
+	find . -type d -name .git -printf '%h\n' | parallel "-j${JOBS}" ${V} -k sh -eo pipefail -c "echo && cd {} && echo {} && ${SCRIPT}"
 elif type xargs &>/dev/null; then
-    find . -type d -name .git -printf '%h\n' | xargs -I {} ${V} "-P${JOBS}" sh -eo pipefail -c "echo && cd {} && echo {} && ${SCRIPT}"
+	find . -type d -name .git -printf '%h\n' | xargs -I {} ${V} "-P${JOBS}" sh -eo pipefail -c "echo && cd {} && echo {} && ${SCRIPT}"
 else
-    find . -type d -name .git -printf '%h\n' | while read d; do
-        (
-            [ "${VERBOSE}" = "1" ] && set -x || true
-            cd "${d}"
-            echo "${d}"
-            "${SCRIPT}"
-        )
-    done
+	find . -type d -name .git -printf '%h\n' | while read d; do
+		(
+			[ "${VERBOSE}" = "1" ] && set -x || true
+			cd "${d}"
+			echo "${d}"
+			"${SCRIPT}"
+		)
+	done
 fi
 rm -f "${SCRIPT}"
